server:
  port: 8080
    context-path:/hdd
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbcrawler?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: 116.62.205.216
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        max-wait: 60000
        min-idle: 1
    database: 0
    password: nBY6GyUr2Epx
