server:
  port: 8080
  servlet:
    context-path: /hdd

spring:
  datasource:
#    url: jdbc:mysql://107.182.187.168:3306/dbhdd?serverTimezone=GMT%2B8
#    username: root
#    password: 094211
    url: jdbc:mysql://116.62.205.216:3306/dbhexuejian?serverTimezone=GMT%2B8
    username: hexuejian
    password: vz#wCgJBjWP3
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
    cache: false
